#!/usr/bin/env bash
# Regenerate catalog/zoo.yaml from the vendor model zoos.
#   Furiosa: furiosa-ai HF org (pre-quantized weights)  — https://huggingface.co/furiosa-ai
#   Rebellions: rbln-model-zoo supported families        — https://github.com/RBLN-SW/rbln-model-zoo
#
# lmd-top itself has no in-binary TLS (glibc-only ethos), so list-fetching lives here (curl has TLS).
# The TUI also refreshes the Furiosa list live via `curl` at runtime; this script keeps the committed
# baseline fresh (and works offline afterwards). Requires: curl, jq.
#
# Usage:  ./scripts/fetch-zoo.sh > catalog/zoo.yaml
set -euo pipefail
have() { command -v "$1" >/dev/null 2>&1; }
have curl || { echo "curl required" >&2; exit 1; }
have jq   || { echo "jq required"   >&2; exit 1; }

FURIOSA_ORG="furiosa-ai"
# rbln-model-zoo text-generation families → representative upstream HF id (RBLN compiles from these).
# Families are discovered live from the repo; the id mapping is maintained here.
declare -A RBLN_MAP=(
  [llama]="meta-llama/Llama-3.1-8B-Instruct"
  [qwen]="Qwen/Qwen2.5-7B-Instruct"
  [gemma2]="google/gemma-2-9b-it"
  [exaone]="LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"
  [mistral]="mistralai/Mistral-7B-Instruct-v0.3"
  [phi]="microsoft/Phi-3.5-mini-instruct"
  [solar]="upstage/SOLAR-10.7B-Instruct-v1.0"
  [opt]="facebook/opt-6.7b"
  [gpt-oss]="openai/gpt-oss-20b"
  [koni]="KISTI-KONI/KONI-Llama3.1-8B-R-Preview-20241024"
)

echo "# Vendor model zoo — auto-generated by scripts/fetch-zoo.sh. Do not hand-edit; re-run the script."
echo "# Sources: furiosa-ai HF org · RBLN-SW/rbln-model-zoo. Override at runtime with LMD_ZOO=<path>."
echo "models:"

# ── Furiosa: HF org, text-generation + embedding + reranker pipelines ──
curl -fsSL "https://huggingface.co/api/models?author=${FURIOSA_ORG}&limit=500" \
  | jq -r '
      map(select(.pipeline_tag=="text-generation" or .pipeline_tag=="sentence-similarity" or .pipeline_tag=="text-classification"))
      | sort_by(-(.downloads // 0))
      | .[]
      | "  - display: \(.id | sub("^furiosa-ai/";"")) (Furiosa)\n    source: \(.id)\n    role: \(if .pipeline_tag=="sentence-similarity" then "embedding" elif .pipeline_tag=="text-classification" then "reranker" else "chat" end)\n    vendor: furiosa\n    note: Furiosa 사전 양자화"
    '

# ── Rebellions: families from rbln-model-zoo → representative upstream HF ids ──
fams=$(curl -fsSL "https://api.github.com/repos/RBLN-SW/rbln-model-zoo/git/trees/main?recursive=1" \
  | jq -r '.tree[] | select(.type=="tree") | .path | select(contains("text-generation/"))
           | sub(".*text-generation/";"") | select(contains("/")|not)' | sort -u)
for fam in $fams; do
  id="${RBLN_MAP[$fam]:-}"
  [ -n "$id" ] || continue
  disp="$(echo "$id" | sed 's#.*/##')"
  printf '  - display: %s (RBLN)\n    source: %s\n    role: chat\n    vendor: rbln\n    note: RBLN 지원 패밀리(%s)\n' "$disp" "$id" "$fam"
done
