#!/usr/bin/env bash
# Regenerate catalog/zoo.yaml from the vendor model zoos.
#   Furiosa: furiosa-ai HF org (pre-quantized weights)  — https://huggingface.co/furiosa-ai
#   Rebellions: rbln-model-zoo supported families        — https://github.com/RBLN-SW/rbln-model-zoo
#
# lmd-top itself has no in-binary TLS (glibc-only ethos), so list-fetching lives here (curl has TLS).
# The TUI also refreshes the Furiosa list live via `curl` at runtime; this script keeps the committed
# baseline fresh (and works offline afterwards). Requires: curl, jq.
#
# Usage:  ./scripts/fetch-zoo.sh > catalog/zoo.yaml
set -euo pipefail
have() { command -v "$1" >/dev/null 2>&1; }
have curl || { echo "curl required" >&2; exit 1; }
have jq   || { echo "jq required"   >&2; exit 1; }

FURIOSA_ORG="furiosa-ai"
RBLN_REPO="RBLN-SW/rbln-model-zoo"
RBLN_RAW="https://raw.githubusercontent.com/${RBLN_REPO}/main"

echo "# Vendor model zoo — auto-generated by scripts/fetch-zoo.sh. Do not hand-edit; re-run the script."
echo "# Sources: furiosa-ai HF org · RBLN-SW/rbln-model-zoo. Override at runtime with LMD_ZOO=<path>."
echo "models:"

# ── Furiosa: HF org, text-generation + embedding + reranker pipelines ──
curl -fsSL "https://huggingface.co/api/models?author=${FURIOSA_ORG}&limit=500" \
  | jq -r '
      map(select(.pipeline_tag=="text-generation" or .pipeline_tag=="sentence-similarity" or .pipeline_tag=="text-classification"))
      | sort_by(-(.downloads // 0))
      | .[]
      | "  - display: \(.id | sub("^furiosa-ai/";"")) (Furiosa)\n    source: \(.id)\n    role: \(if .pipeline_tag=="sentence-similarity" then "embedding" elif .pipeline_tag=="text-classification" then "reranker" else "chat" end)\n    vendor: furiosa\n    note: Furiosa 사전 양자화"
    '

# ── Rebellions: extract the real HF id from each rbln-model-zoo text-gen leaf's compile.py ──
paths=$(curl -fsSL "https://api.github.com/repos/${RBLN_REPO}/git/trees/main?recursive=1" \
  | jq -r '.tree[] | select(.type=="blob") | .path
           | select(test("huggingface/transformers/text2?text-generation/.*/compile\\.py$"))')
echo "$paths" | tr '\n' '\0' | xargs -0 -P 10 -I{} sh -c \
  'curl -fsSL "'"$RBLN_RAW"'/{}" 2>/dev/null | grep -oE "model_id[[:space:]]*=[[:space:]]*\"[^\"]+\"" | head -1 | sed "s/.*\"\([^\"]*\)\".*/\1/"' \
  | grep -E '^[^/]+/[^/]+$' | sort -u | while read -r id; do
      disp="$(echo "$id" | sed 's#.*/##')"
      printf '  - display: %s (RBLN)\n    source: %s\n    role: chat\n    vendor: rbln\n    note: RBLN model zoo\n' "$disp" "$id"
    done
